/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractsContractIdTransactionsTransactionIdGet200Response {
    #[serde(rename = "links")]
    pub links: Box<crate::models::ContractsContractIdTransactionsTransactionIdGet200ResponseLinks>,
    #[serde(rename = "resource")]
    pub resource: Box<crate::models::Tx>,
}

impl ContractsContractIdTransactionsTransactionIdGet200Response {
    pub fn new(links: crate::models::ContractsContractIdTransactionsTransactionIdGet200ResponseLinks, resource: crate::models::Tx) -> ContractsContractIdTransactionsTransactionIdGet200Response {
        ContractsContractIdTransactionsTransactionIdGet200Response {
            links: Box::new(links),
            resource: Box::new(resource),
        }
    }
}


