/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractsContractIdTransactionsPost201ResponseLinks {
    #[serde(rename = "transaction", skip_serializing_if = "Option::is_none")]
    pub transaction: Option<String>,
}

impl ContractsContractIdTransactionsPost201ResponseLinks {
    pub fn new() -> ContractsContractIdTransactionsPost201ResponseLinks {
        ContractsContractIdTransactionsPost201ResponseLinks {
            transaction: None,
        }
    }
}


