/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractsContractIdGet200Response {
    #[serde(rename = "links")]
    pub links: Box<crate::models::ContractsContractIdGet200ResponseLinks>,
    #[serde(rename = "resource")]
    pub resource: Box<crate::models::ContractState>,
}

impl ContractsContractIdGet200Response {
    pub fn new(links: crate::models::ContractsContractIdGet200ResponseLinks, resource: crate::models::ContractState) -> ContractsContractIdGet200Response {
        ContractsContractIdGet200Response {
            links: Box::new(links),
            resource: Box::new(resource),
        }
    }
}


