/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractsPost201ResponseLinks {
    #[serde(rename = "contract", skip_serializing_if = "Option::is_none")]
    pub contract: Option<String>,
}

impl ContractsPost201ResponseLinks {
    pub fn new() -> ContractsPost201ResponseLinks {
        ContractsPost201ResponseLinks {
            contract: None,
        }
    }
}


