/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PayoutsPayoutIdGet200ResponseLinks {
    #[serde(rename = "contract", skip_serializing_if = "Option::is_none")]
    pub contract: Option<String>,
    #[serde(rename = "transaction", skip_serializing_if = "Option::is_none")]
    pub transaction: Option<String>,
    #[serde(rename = "withdrawal", skip_serializing_if = "Option::is_none")]
    pub withdrawal: Option<String>,
}

impl PayoutsPayoutIdGet200ResponseLinks {
    pub fn new() -> PayoutsPayoutIdGet200ResponseLinks {
        PayoutsPayoutIdGet200ResponseLinks {
            contract: None,
            transaction: None,
            withdrawal: None,
        }
    }
}


