/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WithdrawalsPost201Response {
    #[serde(rename = "links")]
    pub links: Box<crate::models::WithdrawalsPost201ResponseLinks>,
    #[serde(rename = "resource")]
    pub resource: Box<crate::models::ApplyInputsTxEnvelope>,
}

impl WithdrawalsPost201Response {
    pub fn new(links: crate::models::WithdrawalsPost201ResponseLinks, resource: crate::models::ApplyInputsTxEnvelope) -> WithdrawalsPost201Response {
        WithdrawalsPost201Response {
            links: Box::new(links),
            resource: Box::new(resource),
        }
    }
}


