/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WithdrawalsPost201ResponseLinks {
    #[serde(rename = "withdrawal", skip_serializing_if = "Option::is_none")]
    pub withdrawal: Option<String>,
}

impl WithdrawalsPost201ResponseLinks {
    pub fn new() -> WithdrawalsPost201ResponseLinks {
        WithdrawalsPost201ResponseLinks {
            withdrawal: None,
        }
    }
}


