/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionOneOf1 {
    #[serde(rename = "choose_between")]
    pub choose_between: Vec<crate::models::Bound>,
    #[serde(rename = "for_choice")]
    pub for_choice: Box<crate::models::ChoiceId>,
}

impl ActionOneOf1 {
    pub fn new(choose_between: Vec<crate::models::Bound>, for_choice: crate::models::ChoiceId) -> ActionOneOf1 {
        ActionOneOf1 {
            choose_between,
            for_choice: Box::new(for_choice),
        }
    }
}


