/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplyInputsResponseLinks {
    #[serde(rename = "transaction", skip_serializing_if = "Option::is_none")]
    pub transaction: Option<String>,
}

impl ApplyInputsResponseLinks {
    pub fn new() -> ApplyInputsResponseLinks {
        ApplyInputsResponseLinks {
            transaction: None,
        }
    }
}


