/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplyInputsResponse {
    #[serde(rename = "links")]
    pub links: Box<crate::models::ApplyInputsResponseLinks>,
    #[serde(rename = "resource")]
    pub resource: Box<crate::models::ApplyInputsTxEnvelope>,
}

impl ApplyInputsResponse {
    pub fn new(
        links: crate::models::ApplyInputsResponseLinks,
        resource: crate::models::ApplyInputsTxEnvelope,
    ) -> ApplyInputsResponse {
        ApplyInputsResponse {
            links: Box::new(links),
            resource: Box::new(resource),
        }
    }
}
