/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ApplicableInputs : Applicable Inputs for a given contract



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicableInputs {
    #[serde(rename = "choices")]
    pub choices: Vec<crate::models::CanChoose>,
    #[serde(rename = "deposits")]
    pub deposits: Vec<crate::models::CanDeposit>,
    #[serde(rename = "notify", skip_serializing_if = "Option::is_none")]
    pub notify: Option<Box<crate::models::CanNotify>>,
}

impl ApplicableInputs {
    /// Applicable Inputs for a given contract
    pub fn new(choices: Vec<crate::models::CanChoose>, deposits: Vec<crate::models::CanDeposit>) -> ApplicableInputs {
        ApplicableInputs {
            choices,
            deposits,
            notify: None,
        }
    }
}


