/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplyInputsTxEnvelope {
    #[serde(rename = "tx")]
    pub tx: Box<crate::models::TextEnvelope>,
    /// The hex-encoded identifier of a Cardano transaction
    #[serde(rename = "withdrawalId")]
    pub withdrawal_id: String,
}

impl ApplyInputsTxEnvelope {
    pub fn new(tx: crate::models::TextEnvelope, withdrawal_id: String) -> ApplyInputsTxEnvelope {
        ApplyInputsTxEnvelope {
            tx: Box::new(tx),
            withdrawal_id,
        }
    }
}


