/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Assets {
    #[serde(rename = "lovelace")]
    pub lovelace: i32,
    #[serde(rename = "tokens")]
    pub tokens: ::std::collections::HashMap<String, ::std::collections::HashMap<String, i32>>,
}

impl Assets {
    pub fn new(lovelace: i32, tokens: ::std::collections::HashMap<String, ::std::collections::HashMap<String, i32>>) -> Assets {
        Assets {
            lovelace,
            tokens,
        }
    }
}


