/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// Assert : Check an observation and produce a warning if it is false.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Assert {
    #[serde(rename = "assert")]
    pub assert: Box<crate::models::Observation>,
    #[serde(rename = "then")]
    pub then: Box<crate::models::Contract>,
}

impl Assert {
    /// Check an observation and produce a warning if it is false.
    pub fn new(assert: crate::models::Observation, then: crate::models::Contract) -> Assert {
        Assert {
            assert: Box::new(assert),
            then: Box::new(then),
        }
    }
}
