/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockHeader {
    #[serde(rename = "blockHeaderHash")]
    pub block_header_hash: String,
    #[serde(rename = "blockNo")]
    pub block_no: i64,
    #[serde(rename = "slotNo")]
    pub slot_no: i64,
}

impl BlockHeader {
    pub fn new(block_header_hash: String, block_no: i64, slot_no: i64) -> BlockHeader {
        BlockHeader {
            block_header_hash,
            block_no,
            slot_no,
        }
    }
}


