/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CanChoose : Choice Inputs that can be applied for a given contract



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CanChoose {
    #[serde(rename = "can_choose_between")]
    pub can_choose_between: Vec<crate::models::Bound>,
    /// Index of a \"Case Action\" in a \"When\"
    #[serde(rename = "case_index")]
    pub case_index: i32,
    #[serde(rename = "for_choice")]
    pub for_choice: Box<crate::models::ChoiceId>,
    /// Indicates if a given contract continuation is merkleized
    #[serde(rename = "is_merkleized_continuation")]
    pub is_merkleized_continuation: bool,
}

impl CanChoose {
    /// Choice Inputs that can be applied for a given contract
    pub fn new(can_choose_between: Vec<crate::models::Bound>, case_index: i32, for_choice: crate::models::ChoiceId, is_merkleized_continuation: bool) -> CanChoose {
        CanChoose {
            can_choose_between,
            case_index,
            for_choice: Box::new(for_choice),
            is_merkleized_continuation,
        }
    }
}


