/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CaseOneOf {
    #[serde(rename = "case")]
    pub case: Box<crate::models::Action>,
    #[serde(rename = "then")]
    pub then: Box<crate::models::Contract>,
}

impl CaseOneOf {
    pub fn new(case: crate::models::Action, then: crate::models::Contract) -> CaseOneOf {
        CaseOneOf {
            case: Box::new(case),
            then: Box::new(then),
        }
    }
}


