/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CaseMerkleizedThenObject {
    #[serde(rename = "case")]
    pub case: Box<crate::models::ActionObject>,
    #[serde(rename = "merkleized_then")]
    pub merkleized_then: String,
}

impl CaseMerkleizedThenObject {
    pub fn new(case: crate::models::ActionObject, merkleized_then: String) -> CaseMerkleizedThenObject {
        CaseMerkleizedThenObject {
            case: Box::new(case),
            merkleized_then,
        }
    }
}


