/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CaseObjectOneOf {
    #[serde(rename = "case")]
    pub case: Box<crate::models::ActionObject>,
    #[serde(rename = "then")]
    pub then: Box<crate::models::ContractObject>,
}

impl CaseObjectOneOf {
    pub fn new(case: crate::models::ActionObject, then: crate::models::ContractObject) -> CaseObjectOneOf {
        CaseObjectOneOf {
            case: Box::new(case),
            then: Box::new(then),
        }
    }
}


