/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CaseMerkleizedThen {
    #[serde(rename = "case")]
    pub case: Box<crate::models::Action>,
    #[serde(rename = "merkleized_then")]
    pub merkleized_then: String,
}

impl CaseMerkleizedThen {
    pub fn new(case: crate::models::Action, merkleized_then: String) -> CaseMerkleizedThen {
        CaseMerkleizedThen {
            case: Box::new(case),
            merkleized_then,
        }
    }
}
