/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CaseObject : A contract which becomes active when an action occurs.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CaseObject {
    #[serde(rename = "case")]
    pub case: Box<crate::models::ActionObject>,
    #[serde(rename = "then")]
    pub then: Box<crate::models::ContractObject>,
    #[serde(rename = "merkleized_then")]
    pub merkleized_then: String,
}

impl CaseObject {
    /// A contract which becomes active when an action occurs.
    pub fn new(case: crate::models::ActionObject, then: crate::models::ContractObject, merkleized_then: String) -> CaseObject {
        CaseObject {
            case: Box::new(case),
            then: Box::new(then),
            merkleized_then,
        }
    }
}


