/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChoiceId : Refers to a party by role name.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChoiceId {
    #[serde(rename = "choice_name")]
    pub choice_name: String,
    #[serde(rename = "choice_owner")]
    pub choice_owner: Box<crate::models::Party>,
}

impl ChoiceId {
    /// Refers to a party by role name.
    pub fn new(choice_name: String, choice_owner: crate::models::Party) -> ChoiceId {
        ChoiceId {
            choice_name,
            choice_owner: Box::new(choice_owner),
        }
    }
}


