/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChoiceAction {
    #[serde(rename = "choose_between")]
    pub choose_between: Vec<crate::models::Bound>,
    #[serde(rename = "for_choice")]
    pub for_choice: Box<crate::models::ChoiceId>,
}

impl ChoiceAction {
    pub fn new(
        choose_between: Vec<crate::models::Bound>,
        for_choice: crate::models::ChoiceId,
    ) -> ChoiceAction {
        ChoiceAction {
            choose_between,
            for_choice: Box::new(for_choice),
        }
    }
}
