/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ContractObjectOneOf4 : Check an observation and produce a warning if it is false.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractObjectOneOf4 {
    #[serde(rename = "assert")]
    pub assert: Box<crate::models::ObservationObject>,
    #[serde(rename = "then")]
    pub then: Box<crate::models::ContractObject>,
}

impl ContractObjectOneOf4 {
    /// Check an observation and produce a warning if it is false.
    pub fn new(assert: crate::models::ObservationObject, then: crate::models::ContractObject) -> ContractObjectOneOf4 {
        ContractObjectOneOf4 {
            assert: Box::new(assert),
            then: Box::new(then),
        }
    }
}


