/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{AssertObject, CloseObject, IfObject, LabelRef, LetObject, PayObject, WhenObject};

/// ContractObject : Contract terms specified in Marlowe

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ContractObject {
    Close(CloseObject),
    Pay(PayObject),
    IfObject(IfObject),
    WhenObject(WhenObject),
    LetObject(LetObject),
    AssertObject(AssertObject),
    LabelRef(LabelRef),
}
