/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// Contract : Contract terms specified in Marlowe

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Contract {
    Close(crate::models::Close),
    Assert(crate::models::Assert),
    When(crate::models::When),
    If(crate::models::If),
    Let(crate::models::Let),
    Pay(crate::models::Pay),
}
