/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// ContractObject : Contract terms specified in Marlowe

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ContractObject {
    Close(crate::models::CloseObject),
    Pay(crate::models::PayObject),
    IfObject(crate::models::IfObject),
    WhenObject(crate::models::WhenObject),
    LetObject(crate::models::LetObject),
    AssertObject(crate::models::AssertObject),
    LabelRef(crate::models::LabelRef),
}
