/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ContractOneOf : A payment will be sent from an account to a payee.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractOneOf {
    #[serde(rename = "from_account")]
    pub from_account: Box<crate::models::Party>,
    #[serde(rename = "pay")]
    pub pay: Box<crate::models::Value>,
    #[serde(rename = "then")]
    pub then: Box<crate::models::Contract>,
    #[serde(rename = "to")]
    pub to: Box<crate::models::Payee>,
    #[serde(rename = "token")]
    pub token: Box<crate::models::Token>,
}

impl ContractOneOf {
    /// A payment will be sent from an account to a payee.
    pub fn new(from_account: crate::models::Party, pay: crate::models::Value, then: crate::models::Contract, to: crate::models::Payee, token: crate::models::Token) -> ContractOneOf {
        ContractOneOf {
            from_account: Box::new(from_account),
            pay: Box::new(pay),
            then: Box::new(then),
            to: Box::new(to),
            token: Box::new(token),
        }
    }
}


