/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ContractObjectOneOf : A payment will be sent from an account to a payee.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractObjectOneOf {
    #[serde(rename = "from_account")]
    pub from_account: Box<crate::models::PartyObject>,
    #[serde(rename = "pay")]
    pub pay: Box<crate::models::ValueObject>,
    #[serde(rename = "then")]
    pub then: Box<crate::models::ContractObject>,
    #[serde(rename = "to")]
    pub to: Box<crate::models::PayeeObject>,
    #[serde(rename = "token")]
    pub token: Box<crate::models::TokenObject>,
}

impl ContractObjectOneOf {
    /// A payment will be sent from an account to a payee.
    pub fn new(from_account: crate::models::PartyObject, pay: crate::models::ValueObject, then: crate::models::ContractObject, to: crate::models::PayeeObject, token: crate::models::TokenObject) -> ContractObjectOneOf {
        ContractObjectOneOf {
            from_account: Box::new(from_account),
            pay: Box::new(pay),
            then: Box::new(then),
            to: Box::new(to),
            token: Box::new(token),
        }
    }
}


