/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{Assert, Close, If, Let, Pay, When};

/// Contract : Contract terms specified in Marlowe

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Contract {
    Close(Close),
    Assert(Assert),
    When(When),
    If(If),
    Let(Let),
    Pay(Pay),
}
