/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Divide {
    #[serde(rename = "by")]
    pub by: Box<crate::models::Value>,
    #[serde(rename = "divide")]
    pub divide: Box<crate::models::Value>,
}

impl Divide {
    pub fn new(by: crate::models::Value, divide: crate::models::Value) -> Divide {
        Divide {
            by: Box::new(by),
            divide: Box::new(divide),
        }
    }
}


