/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExBudget {
    #[serde(rename = "exBudgetCPU")]
    pub ex_budget_cpu: f32,
    #[serde(rename = "exBudgetMemory")]
    pub ex_budget_memory: f32,
}

impl ExBudget {
    pub fn new(ex_budget_cpu: f32, ex_budget_memory: f32) -> ExBudget {
        ExBudget {
            ex_budget_cpu,
            ex_budget_memory,
        }
    }
}


