/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractResponse {
    #[serde(rename = "links")]
    pub links: Box<crate::models::GetContractResponseLinks>,
    #[serde(rename = "resource")]
    pub resource: Box<crate::models::ContractState>,
}

impl GetContractResponse {
    pub fn new(links: crate::models::GetContractResponseLinks, resource: crate::models::ContractState) -> GetContractResponse {
        GetContractResponse {
            links: Box::new(links),
            resource: Box::new(resource),
        }
    }
}


