/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTransactionResponse {
    #[serde(rename = "links")]
    pub links: Box<crate::models::GetTransactionResponseLinks>,
    #[serde(rename = "resource")]
    pub resource: Box<crate::models::Tx>,
}

impl GetTransactionResponse {
    pub fn new(
        links: crate::models::GetTransactionResponseLinks,
        resource: crate::models::Tx,
    ) -> GetTransactionResponse {
        GetTransactionResponse {
            links: Box::new(links),
            resource: Box::new(resource),
        }
    }
}
