/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPayoutResponse {
    #[serde(rename = "links")]
    pub links: Box<crate::models::GetPayoutResponseLinks>,
    #[serde(rename = "resource")]
    pub resource: Box<crate::models::PayoutState>,
}

impl GetPayoutResponse {
    pub fn new(links: crate::models::GetPayoutResponseLinks, resource: crate::models::PayoutState) -> GetPayoutResponse {
        GetPayoutResponse {
            links: Box::new(links),
            resource: Box::new(resource),
        }
    }
}


