/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Greater {
    #[serde(rename = "gt")]
    pub gt: Box<crate::models::Value>,
    #[serde(rename = "value")]
    pub value: Box<crate::models::Value>,
}

impl Greater {
    pub fn new(gt: crate::models::Value, value: crate::models::Value) -> Greater {
        Greater {
            gt: Box::new(gt),
            value: Box::new(value),
        }
    }
}


