/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IfValueObject {
    #[serde(rename = "else")]
    pub r#else: Box<crate::models::ValueObject>,
    #[serde(rename = "if")]
    pub r#if: Box<crate::models::ObservationObject>,
    #[serde(rename = "then")]
    pub then: Box<crate::models::ValueObject>,
}

impl IfValueObject {
    pub fn new(
        r#else: crate::models::ValueObject,
        r#if: crate::models::ObservationObject,
        then: crate::models::ValueObject,
    ) -> IfValueObject {
        IfValueObject {
            r#else: Box::new(r#else),
            r#if: Box::new(r#if),
            then: Box::new(then),
        }
    }
}
