/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// InputOneOf2 : Make a choice in a contract



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputOneOf2 {
    #[serde(rename = "for_choice_id")]
    pub for_choice_id: Box<crate::models::ChoiceId>,
    #[serde(rename = "input_that_chooses_num")]
    pub input_that_chooses_num: i32,
}

impl InputOneOf2 {
    /// Make a choice in a contract
    pub fn new(for_choice_id: crate::models::ChoiceId, input_that_chooses_num: i32) -> InputOneOf2 {
        InputOneOf2 {
            for_choice_id: Box::new(for_choice_id),
            input_that_chooses_num,
        }
    }
}


