/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// Input : An input to a Marlowe transaction

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Input {
    #[serde(rename = "continuation_hash")]
    pub continuation_hash: String,
    #[serde(rename = "merkleized_continuation")]
    pub merkleized_continuation: Box<crate::models::Contract>,
    #[serde(rename = "for_choice_id")]
    pub for_choice_id: Box<crate::models::ChoiceId>,
    #[serde(rename = "input_that_chooses_num")]
    pub input_that_chooses_num: i32,
    #[serde(rename = "input_from_party")]
    pub input_from_party: Box<crate::models::Party>,
    #[serde(rename = "into_account")]
    pub into_account: Box<crate::models::Party>,
    #[serde(rename = "of_token")]
    pub of_token: Box<crate::models::Token>,
    #[serde(rename = "that_deposits")]
    pub that_deposits: i32,
}

impl Input {
    /// An input to a Marlowe transaction
    pub fn new(
        continuation_hash: String,
        merkleized_continuation: crate::models::Contract,
        for_choice_id: crate::models::ChoiceId,
        input_that_chooses_num: i32,
        input_from_party: crate::models::Party,
        into_account: crate::models::Party,
        of_token: crate::models::Token,
        that_deposits: i32,
    ) -> Input {
        Input {
            continuation_hash,
            merkleized_continuation: Box::new(merkleized_continuation),
            for_choice_id: Box::new(for_choice_id),
            input_that_chooses_num,
            input_from_party: Box::new(input_from_party),
            into_account: Box::new(into_account),
            of_token: Box::new(of_token),
            that_deposits,
        }
    }
}
