/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// InputOneOf4 : Deposit funds into an account in a contract



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputOneOf4 {
    #[serde(rename = "input_from_party")]
    pub input_from_party: Box<crate::models::Party>,
    #[serde(rename = "into_account")]
    pub into_account: Box<crate::models::Party>,
    #[serde(rename = "of_token")]
    pub of_token: Box<crate::models::Token>,
    #[serde(rename = "that_deposits")]
    pub that_deposits: i32,
}

impl InputOneOf4 {
    /// Deposit funds into an account in a contract
    pub fn new(input_from_party: crate::models::Party, into_account: crate::models::Party, of_token: crate::models::Token, that_deposits: i32) -> InputOneOf4 {
        InputOneOf4 {
            input_from_party: Box::new(input_from_party),
            into_account: Box::new(into_account),
            of_token: Box::new(of_token),
            that_deposits,
        }
    }
}


