/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{
    ChoiceContinuationInput, ChoiceInput, ContinuationInput, DepositContinuationInput,
    DepositInput, NotifyInput,
};

/// Input : An input to a Marlowe transaction

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Input {
    ContinuationInput(ContinuationInput),
    NotifyInput(NotifyInput),
    ChoiceContinuationInput(ChoiceContinuationInput),
    ChoiceInput(ChoiceInput),
    DepositInput(DepositInput),
    DepositContinuationInput(DepositContinuationInput),
}
