/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// Input : An input to a Marlowe transaction

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Input {
    ContinuationInput(crate::models::ContinuationInput),
    NotifyInput(crate::models::NotifyInput),
    ChoiceContinuationInput(crate::models::ChoiceContinuationInput),
    ChoiceInput(crate::models::ChoiceInput),
    DepositInput(crate::models::DepositInput),
    DepositContinuationInput(crate::models::DepositContinuationInput),
}
