/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IntervalErrorOneOf : Invalid Marlowe transaction interval.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntervalErrorOneOf {
    #[serde(rename = "invalidInterval")]
    pub invalid_interval: Box<crate::models::IntervalErrorOneOfInvalidInterval>,
}

impl IntervalErrorOneOf {
    /// Invalid Marlowe transaction interval.
    pub fn new(invalid_interval: crate::models::IntervalErrorOneOfInvalidInterval) -> IntervalErrorOneOf {
        IntervalErrorOneOf {
            invalid_interval: Box::new(invalid_interval),
        }
    }
}


