/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntervalErrorOneOfInvalidInterval {
    #[serde(rename = "from")]
    pub from: i32,
    #[serde(rename = "to")]
    pub to: i32,
}

impl IntervalErrorOneOfInvalidInterval {
    pub fn new(from: i32, to: i32) -> IntervalErrorOneOfInvalidInterval {
        IntervalErrorOneOfInvalidInterval {
            from,
            to,
        }
    }
}


