/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IntervalError : A Marlowe transaction interval error.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntervalError {
    #[serde(rename = "invalidInterval")]
    pub invalid_interval: Box<crate::models::InvalidIntervalInvalidInterval>,
    #[serde(rename = "intervalInPastError")]
    pub interval_in_past_error: Box<crate::models::IntervalInPastIntervalInPastError>,
}

impl IntervalError {
    /// A Marlowe transaction interval error.
    pub fn new(invalid_interval: crate::models::InvalidIntervalInvalidInterval, interval_in_past_error: crate::models::IntervalInPastIntervalInPastError) -> IntervalError {
        IntervalError {
            invalid_interval: Box::new(invalid_interval),
            interval_in_past_error: Box::new(interval_in_past_error),
        }
    }
}


