/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IntervalError : A Marlowe transaction interval error.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntervalError {
    #[serde(rename = "invalidInterval")]
    pub invalid_interval: Box<crate::models::IntervalErrorOneOfInvalidInterval>,
    #[serde(rename = "intervalInPastError")]
    pub interval_in_past_error: Box<crate::models::IntervalErrorOneOf1IntervalInPastError>,
}

impl IntervalError {
    /// A Marlowe transaction interval error.
    pub fn new(invalid_interval: crate::models::IntervalErrorOneOfInvalidInterval, interval_in_past_error: crate::models::IntervalErrorOneOf1IntervalInPastError) -> IntervalError {
        IntervalError {
            invalid_interval: Box::new(invalid_interval),
            interval_in_past_error: Box::new(interval_in_past_error),
        }
    }
}


