/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// InvalidInterval : Invalid Marlowe transaction interval.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidInterval {
    #[serde(rename = "invalidInterval")]
    pub invalid_interval: Box<crate::models::InvalidIntervalInvalidInterval>,
}

impl InvalidInterval {
    /// Invalid Marlowe transaction interval.
    pub fn new(invalid_interval: crate::models::InvalidIntervalInvalidInterval) -> InvalidInterval {
        InvalidInterval {
            invalid_interval: Box::new(invalid_interval),
        }
    }
}


