/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LabelledObjectValue {
    ValueObject(crate::models::ValueObject),
    ObservationObject(crate::models::ObservationObject),
    ContractObject(crate::models::ContractObject),
    PartyObject(crate::models::PartyObject),
    TokenObject(crate::models::TokenObject),
    ActionObject(crate::models::ActionObject),
}
