/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LesserObject {
    #[serde(rename = "lt")]
    pub lt: Box<crate::models::ValueObject>,
    #[serde(rename = "value")]
    pub value: Box<crate::models::ValueObject>,
}

impl LesserObject {
    pub fn new(lt: crate::models::ValueObject, value: crate::models::ValueObject) -> LesserObject {
        LesserObject {
            lt: Box::new(lt),
            value: Box::new(value),
        }
    }
}
