/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Lesser {
    #[serde(rename = "lt")]
    pub lt: Box<crate::models::Value>,
    #[serde(rename = "value")]
    pub value: Box<crate::models::Value>,
}

impl Lesser {
    pub fn new(lt: crate::models::Value, value: crate::models::Value) -> Lesser {
        Lesser {
            lt: Box::new(lt),
            value: Box::new(value),
        }
    }
}


