/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListObjectContractSourceId {
    #[serde(rename = "results")]
    pub results: Vec<String>,
}

impl ListObjectContractSourceId {
    pub fn new(results: Vec<String>) -> ListObjectContractSourceId {
        ListObjectContractSourceId {
            results,
        }
    }
}


