/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// MarloweState : The on-chain state of a Marlowe contract.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarloweState {
    #[serde(rename = "accounts")]
    pub accounts: Vec<crate::models::MarloweStateAccountsInnerInner>,
    #[serde(rename = "boundValues")]
    pub bound_values: Vec<crate::models::MarloweStateBoundValuesInnerInner>,
    #[serde(rename = "choices")]
    pub choices: Vec<crate::models::MarloweStateChoicesInnerInner>,
    #[serde(rename = "minTime")]
    pub min_time: i32,
}

impl MarloweState {
    /// The on-chain state of a Marlowe contract.
    pub fn new(
        accounts: Vec<crate::models::MarloweStateAccountsInnerInner>,
        bound_values: Vec<crate::models::MarloweStateBoundValuesInnerInner>,
        choices: Vec<crate::models::MarloweStateChoicesInnerInner>,
        min_time: i32,
    ) -> MarloweState {
        MarloweState {
            accounts,
            bound_values,
            choices,
            min_time,
        }
    }
}
