/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarloweStateChoicesInnerInner {
    #[serde(rename = "choice_name")]
    pub choice_name: String,
    #[serde(rename = "choice_owner")]
    pub choice_owner: Box<crate::models::Party>,
}

impl MarloweStateChoicesInnerInner {
    pub fn new(choice_name: String, choice_owner: crate::models::Party) -> MarloweStateChoicesInnerInner {
        MarloweStateChoicesInnerInner {
            choice_name,
            choice_owner: Box::new(choice_owner),
        }
    }
}


