/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarloweStateAccountsInnerInnerOneOfInner {
    #[serde(rename = "role_token")]
    pub role_token: String,
    /// A cardano address
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "currency_symbol")]
    pub currency_symbol: String,
    #[serde(rename = "token_name")]
    pub token_name: String,
}

impl MarloweStateAccountsInnerInnerOneOfInner {
    pub fn new(role_token: String, address: String, currency_symbol: String, token_name: String) -> MarloweStateAccountsInnerInnerOneOfInner {
        MarloweStateAccountsInnerInnerOneOfInner {
            role_token,
            address,
            currency_symbol,
            token_name,
        }
    }
}


