/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// MarloweVersion : A version of the Marlowe language.

/// A version of the Marlowe language.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MarloweVersion {
    #[serde(rename = "v1")]
    V1,
}

impl ToString for MarloweVersion {
    fn to_string(&self) -> String {
        match self {
            Self::V1 => String::from("v1"),
        }
    }
}

impl Default for MarloweVersion {
    fn default() -> MarloweVersion {
        Self::V1
    }
}
