/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetadataAndRecipients {
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::models::TokenMetadata>,
    #[serde(rename = "recipients")]
    pub recipients: ::std::collections::HashMap<String, i64>,
}

impl MetadataAndRecipients {
    pub fn new(recipients: ::std::collections::HashMap<String, i64>) -> MetadataAndRecipients {
        MetadataAndRecipients {
            metadata: None,
            recipients,
        }
    }
}


