/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Metadata : Arbitrary JSON-encoded transaction metadata



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Metadata {
}

impl Metadata {
    /// Arbitrary JSON-encoded transaction metadata
    pub fn new() -> Metadata {
        Metadata {
        }
    }
}


