/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NegateObject {
    #[serde(rename = "negate")]
    pub negate: Box<crate::models::ValueObject>,
}

impl NegateObject {
    pub fn new(negate: crate::models::ValueObject) -> NegateObject {
        NegateObject {
            negate: Box::new(negate),
        }
    }
}
