/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Next : Describe the reducibility (Can be Reduced ?) and the applicability (Can Inputs be Applied ?) for a given contract.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Next {
    #[serde(rename = "applicable_inputs")]
    pub applicable_inputs: Box<crate::models::ApplicableInputs>,
    /// Indicates if a given contract can be reduced (apply []) or not.
    #[serde(rename = "can_reduce")]
    pub can_reduce: bool,
}

impl Next {
    /// Describe the reducibility (Can be Reduced ?) and the applicability (Can Inputs be Applied ?) for a given contract.
    pub fn new(applicable_inputs: crate::models::ApplicableInputs, can_reduce: bool) -> Next {
        Next {
            applicable_inputs: Box::new(applicable_inputs),
            can_reduce,
        }
    }
}


