/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Not {
    #[serde(rename = "not")]
    pub not: Box<crate::models::Observation>,
}

impl Not {
    pub fn new(not: crate::models::Observation) -> Not {
        Not {
            not: Box::new(not),
        }
    }
}


