/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObservationObjectOneOf {
    #[serde(rename = "and")]
    pub and: Box<crate::models::ObservationObject>,
    #[serde(rename = "both")]
    pub both: Box<crate::models::ObservationObject>,
}

impl ObservationObjectOneOf {
    pub fn new(and: crate::models::ObservationObject, both: crate::models::ObservationObject) -> ObservationObjectOneOf {
        ObservationObjectOneOf {
            and: Box::new(and),
            both: Box::new(both),
        }
    }
}


