/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObservationObjectOneOf7 {
    #[serde(rename = "le_than")]
    pub le_than: Box<crate::models::ValueObject>,
    #[serde(rename = "value")]
    pub value: Box<crate::models::ValueObject>,
}

impl ObservationObjectOneOf7 {
    pub fn new(le_than: crate::models::ValueObject, value: crate::models::ValueObject) -> ObservationObjectOneOf7 {
        ObservationObjectOneOf7 {
            le_than: Box::new(le_than),
            value: Box::new(value),
        }
    }
}


