/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObservationOneOf1 {
    #[serde(rename = "either")]
    pub either: Box<crate::models::Observation>,
    #[serde(rename = "or")]
    pub or: Box<crate::models::Observation>,
}

impl ObservationOneOf1 {
    pub fn new(either: crate::models::Observation, or: crate::models::Observation) -> ObservationOneOf1 {
        ObservationOneOf1 {
            either: Box::new(either),
            or: Box::new(or),
        }
    }
}


