/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObservationObjectOneOf4 {
    #[serde(rename = "ge_than")]
    pub ge_than: Box<crate::models::ValueObject>,
    #[serde(rename = "value")]
    pub value: Box<crate::models::ValueObject>,
}

impl ObservationObjectOneOf4 {
    pub fn new(ge_than: crate::models::ValueObject, value: crate::models::ValueObject) -> ObservationObjectOneOf4 {
        ObservationObjectOneOf4 {
            ge_than: Box::new(ge_than),
            value: Box::new(value),
        }
    }
}


