/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// Observation : A time-varying expression that evaluates to an integer

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Observation {
    Boolean(bool),
    And(crate::models::And),
    Or(crate::models::Or),
    Not(crate::models::Not),
    ChooseFor(crate::models::ChooseFor),
    GreaterOrEqual(crate::models::GreaterOrEqual),
    Greater(crate::models::Greater),
    Lesser(crate::models::Lesser),
    LesserOrEqual(crate::models::LesserOrEqual),
    Equal(crate::models::Equal),
}
