/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObservationOneOf {
    #[serde(rename = "and")]
    pub and: Box<crate::models::Observation>,
    #[serde(rename = "both")]
    pub both: Box<crate::models::Observation>,
}

impl ObservationOneOf {
    pub fn new(and: crate::models::Observation, both: crate::models::Observation) -> ObservationOneOf {
        ObservationOneOf {
            and: Box::new(and),
            both: Box::new(both),
        }
    }
}


