/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObservationObjectOneOf2 {
    #[serde(rename = "not")]
    pub not: Box<crate::models::ObservationObject>,
}

impl ObservationObjectOneOf2 {
    pub fn new(not: crate::models::ObservationObject) -> ObservationObjectOneOf2 {
        ObservationObjectOneOf2 {
            not: Box::new(not),
        }
    }
}


