/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObservationOneOf8 {
    #[serde(rename = "equal_to")]
    pub equal_to: Box<crate::models::Value>,
    #[serde(rename = "value")]
    pub value: Box<crate::models::Value>,
}

impl ObservationOneOf8 {
    pub fn new(equal_to: crate::models::Value, value: crate::models::Value) -> ObservationOneOf8 {
        ObservationOneOf8 {
            equal_to: Box::new(equal_to),
            value: Box::new(value),
        }
    }
}


