/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObservationObjectOneOf2 {
    #[serde(rename = "not")]
    pub not: Box<crate::models::ObservationObject>,
}

impl ObservationObjectOneOf2 {
    pub fn new(not: crate::models::ObservationObject) -> ObservationObjectOneOf2 {
        ObservationObjectOneOf2 {
            not: Box::new(not),
        }
    }
}


