/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObservationOneOf5 {
    #[serde(rename = "gt")]
    pub gt: Box<crate::models::Value>,
    #[serde(rename = "value")]
    pub value: Box<crate::models::Value>,
}

impl ObservationOneOf5 {
    pub fn new(gt: crate::models::Value, value: crate::models::Value) -> ObservationOneOf5 {
        ObservationOneOf5 {
            gt: Box::new(gt),
            value: Box::new(value),
        }
    }
}


