/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{
    AndObject, ChooseForObject, EqualObject, GreaterObject, GreaterOrEqualObject, LabelRef,
    LesserObject, LesserOrEqualObject, NotObject, OrObject,
};

/// ObservationObject : A time-varying expression that evaluates to an integer

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObservationObject {
    Boolean(bool),
    AndObject(AndObject),
    OrObject(OrObject),
    NotObject(NotObject),
    ChooseForObject(ChooseForObject),
    GreaterOrEqualObject(GreaterOrEqualObject),
    GreaterObject(GreaterObject),
    LesserObject(LesserObject),
    LesserOrEqualObject(LesserOrEqualObject),
    EqualObject(EqualObject),
    LabelRef(LabelRef),
}
