/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// ObservationObject : A time-varying expression that evaluates to an integer

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObservationObject {
    Boolean(bool),
    AndObject(crate::models::AndObject),
    OrObject(crate::models::OrObject),
    NotObject(crate::models::NotObject),
    ChooseForObject(crate::models::ChooseForObject),
    GreaterOrEqualObject(crate::models::GreaterOrEqualObject),
    GreaterObject(crate::models::GreaterObject),
    LesserObject(crate::models::LesserObject),
    LesserOrEqualObject(crate::models::LesserOrEqualObject),
    EqualObject(crate::models::EqualObject),
    LabelRef(crate::models::LabelRef),
}
