/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObservationOneOf6 {
    #[serde(rename = "lt")]
    pub lt: Box<crate::models::Value>,
    #[serde(rename = "value")]
    pub value: Box<crate::models::Value>,
}

impl ObservationOneOf6 {
    pub fn new(lt: crate::models::Value, value: crate::models::Value) -> ObservationOneOf6 {
        ObservationOneOf6 {
            lt: Box::new(lt),
            value: Box::new(value),
        }
    }
}


