/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Or {
    #[serde(rename = "either")]
    pub either: Box<crate::models::Observation>,
    #[serde(rename = "or")]
    pub or: Box<crate::models::Observation>,
}

impl Or {
    pub fn new(either: crate::models::Observation, or: crate::models::Observation) -> Or {
        Or {
            either: Box::new(either),
            or: Box::new(or),
        }
    }
}
