/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrObject {
    #[serde(rename = "either")]
    pub either: Box<crate::models::ObservationObject>,
    #[serde(rename = "or")]
    pub or: Box<crate::models::ObservationObject>,
}

impl OrObject {
    pub fn new(
        either: crate::models::ObservationObject,
        or: crate::models::ObservationObject,
    ) -> OrObject {
        OrObject {
            either: Box::new(either),
            or: Box::new(or),
        }
    }
}
