/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// Party : A participant in a contract

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Party {
    #[serde(rename = "role_token")]
    pub role_token: String,
    /// A cardano address, in Bech32 format
    #[serde(rename = "address")]
    pub address: String,
}

impl Party {
    /// A participant in a contract
    pub fn new(role_token: String, address: String) -> Party {
        Party {
            role_token,
            address,
        }
    }
}
