/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PartyOneOf : Refers to a party by role name.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartyOneOf {
    #[serde(rename = "role_token")]
    pub role_token: String,
}

impl PartyOneOf {
    /// Refers to a party by role name.
    pub fn new(role_token: String) -> PartyOneOf {
        PartyOneOf {
            role_token,
        }
    }
}


