/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// PartyRoleName : Refers to a party by role name.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartyRoleName {
    #[serde(rename = "role_token")]
    pub role_token: String,
}

impl PartyRoleName {
    /// Refers to a party by role name.
    pub fn new(role_token: String) -> PartyRoleName {
        PartyRoleName { role_token }
    }
}
