/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PartyObject : A participant in a contract



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartyObject {
    #[serde(rename = "role_token")]
    pub role_token: String,
    /// A cardano address, in Bech32 format
    #[serde(rename = "address")]
    pub address: String,
    /// An arbitrary text identifier for an object in a Marlowe object bundle.
    #[serde(rename = "ref")]
    pub r#ref: String,
}

impl PartyObject {
    /// A participant in a contract
    pub fn new(role_token: String, address: String, r#ref: String) -> PartyObject {
        PartyObject {
            role_token,
            address,
            r#ref,
        }
    }
}


