/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// PartyAddress : Refers to a party by Cardano address.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartyAddress {
    /// A cardano address, in Bech32 format
    #[serde(rename = "address")]
    pub address: String,
}

impl PartyAddress {
    /// Refers to a party by Cardano address.
    pub fn new(address: String) -> PartyAddress {
        PartyAddress { address }
    }
}
