/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PayObject : A payment will be sent from an account to a payee.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PayObject {
    #[serde(rename = "from_account")]
    pub from_account: Box<crate::models::PartyObject>,
    #[serde(rename = "pay")]
    pub pay: Box<crate::models::ValueObject>,
    #[serde(rename = "then")]
    pub then: Box<crate::models::ContractObject>,
    #[serde(rename = "to")]
    pub to: Box<crate::models::PayeeObject>,
    #[serde(rename = "token")]
    pub token: Box<crate::models::TokenObject>,
}

impl PayObject {
    /// A payment will be sent from an account to a payee.
    pub fn new(from_account: crate::models::PartyObject, pay: crate::models::ValueObject, then: crate::models::ContractObject, to: crate::models::PayeeObject, token: crate::models::TokenObject) -> PayObject {
        PayObject {
            from_account: Box::new(from_account),
            pay: Box::new(pay),
            then: Box::new(then),
            to: Box::new(to),
            token: Box::new(token),
        }
    }
}


