/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// PayToParty : Pays funds to a party.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PayToParty {
    #[serde(rename = "party")]
    pub party: Box<crate::models::Party>,
}

impl PayToParty {
    /// Pays funds to a party.
    pub fn new(party: crate::models::Party) -> PayToParty {
        PayToParty {
            party: Box::new(party),
        }
    }
}
