/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PayeeObjectOneOf1 : Pays funds to a party.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PayeeObjectOneOf1 {
    #[serde(rename = "party")]
    pub party: Box<crate::models::PartyObject>,
}

impl PayeeObjectOneOf1 {
    /// Pays funds to a party.
    pub fn new(party: crate::models::PartyObject) -> PayeeObjectOneOf1 {
        PayeeObjectOneOf1 {
            party: Box::new(party),
        }
    }
}


