/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{PayToAccount, PayToParty};

/// Payee : A recipient of a payment

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Payee {
    PayToAccount(Box<PayToAccount>),
    PayToParty(Box<PayToParty>),
}
