/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// PayoutStatus : The status of a payout. Either it is available to be withdrawn, or it has already been withdrawn.

/// The status of a payout. Either it is available to be withdrawn, or it has already been withdrawn.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PayoutStatus {
    #[serde(rename = "available")]
    Available,
    #[serde(rename = "withdrawn")]
    Withdrawn,
}

impl ToString for PayoutStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Available => String::from("available"),
            Self::Withdrawn => String::from("withdrawn"),
        }
    }
}

impl Default for PayoutStatus {
    fn default() -> PayoutStatus {
        Self::Available
    }
}
