/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Payout {
    #[serde(rename = "assets")]
    pub assets: Box<crate::models::Assets>,
    /// A reference to a transaction output with a transaction ID and index.
    #[serde(rename = "payoutId")]
    pub payout_id: String,
    #[serde(rename = "role")]
    pub role: String,
}

impl Payout {
    pub fn new(assets: crate::models::Assets, payout_id: String, role: String) -> Payout {
        Payout {
            assets: Box::new(assets),
            payout_id,
            role,
        }
    }
}


