/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PlutusStakingCredentialOneOf : A Plutus staking hash.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlutusStakingCredentialOneOf {
    #[serde(rename = "stakingHash")]
    pub staking_hash: Box<crate::models::PlutusPeriodCredential>,
}

impl PlutusStakingCredentialOneOf {
    /// A Plutus staking hash.
    pub fn new(staking_hash: crate::models::PlutusPeriodCredential) -> PlutusStakingCredentialOneOf {
        PlutusStakingCredentialOneOf {
            staking_hash: Box::new(staking_hash),
        }
    }
}


