/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PlutusPeriodStakingCredential : A Plutus staking credential.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlutusPeriodStakingCredential {
    #[serde(rename = "stakingHash")]
    pub staking_hash: Vec<crate::models::PlutusStakingCredentialOneOf1StakingHashInner>,
}

impl PlutusPeriodStakingCredential {
    /// A Plutus staking credential.
    pub fn new(staking_hash: Vec<crate::models::PlutusStakingCredentialOneOf1StakingHashInner>) -> PlutusPeriodStakingCredential {
        PlutusPeriodStakingCredential {
            staking_hash,
        }
    }
}


