/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PlutusStakingCredentialOneOf1 : A Plutus staking pointer.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlutusStakingCredentialOneOf1 {
    #[serde(rename = "stakingHash")]
    pub staking_hash: Vec<i32>,
}

impl PlutusStakingCredentialOneOf1 {
    /// A Plutus staking pointer.
    pub fn new(staking_hash: Vec<i32>) -> PlutusStakingCredentialOneOf1 {
        PlutusStakingCredentialOneOf1 {
            staking_hash,
        }
    }
}


