/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// PlutusPeriodCredential : A Plutus credential.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlutusPeriodCredential {
    #[serde(rename = "pubKeyCredential")]
    pub pub_key_credential: String,
    #[serde(rename = "scriptCredential")]
    pub script_credential: String,
}

impl PlutusPeriodCredential {
    /// A Plutus credential.
    pub fn new(pub_key_credential: String, script_credential: String) -> PlutusPeriodCredential {
        PlutusPeriodCredential {
            pub_key_credential,
            script_credential,
        }
    }
}
