/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlutusStakingCredentialOneOf1StakingHashInner {
}

impl PlutusStakingCredentialOneOf1StakingHashInner {
    pub fn new() -> PlutusStakingCredentialOneOf1StakingHashInner {
        PlutusStakingCredentialOneOf1StakingHashInner {
        }
    }
}


