/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PlutusCredentialOneOf : A Plutus public key credential.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlutusCredentialOneOf {
    #[serde(rename = "pubKeyCredential")]
    pub pub_key_credential: String,
}

impl PlutusCredentialOneOf {
    /// A Plutus public key credential.
    pub fn new(pub_key_credential: String) -> PlutusCredentialOneOf {
        PlutusCredentialOneOf {
            pub_key_credential,
        }
    }
}


