/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PlutusPeriodStakingCredential : A Plutus staking credential.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlutusPeriodStakingCredential {
    #[serde(rename = "stakingHash")]
    pub staking_hash: Vec<i32>,
}

impl PlutusPeriodStakingCredential {
    /// A Plutus staking credential.
    pub fn new(staking_hash: Vec<i32>) -> PlutusPeriodStakingCredential {
        PlutusPeriodStakingCredential {
            staking_hash,
        }
    }
}


