/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PlutusPeriodAddress : A Plutus address.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlutusPeriodAddress {
    #[serde(rename = "addressCredential")]
    pub address_credential: Box<crate::models::PlutusPeriodCredential>,
    #[serde(rename = "addressStakingCredential", skip_serializing_if = "Option::is_none")]
    pub address_staking_credential: Option<Box<crate::models::PlutusPeriodStakingCredential>>,
}

impl PlutusPeriodAddress {
    /// A Plutus address.
    pub fn new(address_credential: crate::models::PlutusPeriodCredential) -> PlutusPeriodAddress {
        PlutusPeriodAddress {
            address_credential: Box::new(address_credential),
            address_staking_credential: None,
        }
    }
}


