/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostContractSourceResponse {
    /// The hex-encoded identifier of a Marlowe contract source
    #[serde(rename = "contractSourceId")]
    pub contract_source_id: String,
    #[serde(rename = "intermediateIds")]
    pub intermediate_ids: ::std::collections::HashMap<String, String>,
}

impl PostContractSourceResponse {
    pub fn new(contract_source_id: String, intermediate_ids: ::std::collections::HashMap<String, String>) -> PostContractSourceResponse {
        PostContractSourceResponse {
            contract_source_id,
            intermediate_ids,
        }
    }
}


