/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostContractsRequest {
    #[serde(rename = "contract")]
    pub contract: Box<crate::models::PostContractsRequestContract>,
    #[serde(rename = "metadata")]
    pub metadata: ::std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "minUTxODeposit")]
    pub min_utx_o_deposit: i64,
    #[serde(rename = "roles", skip_serializing_if = "Option::is_none")]
    pub roles: Option<Box<crate::models::RolesConfig>>,
    #[serde(rename = "tags")]
    pub tags: ::std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "version")]
    pub version: crate::models::MarloweVersion,
}

impl PostContractsRequest {
    pub fn new(contract: crate::models::PostContractsRequestContract, metadata: ::std::collections::HashMap<String, serde_json::Value>, min_utx_o_deposit: i64, tags: ::std::collections::HashMap<String, serde_json::Value>, version: crate::models::MarloweVersion) -> PostContractsRequest {
        PostContractsRequest {
            contract: Box::new(contract),
            metadata,
            min_utx_o_deposit,
            roles: None,
            tags,
            version,
        }
    }
}


