/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostTransactionsRequest {
    #[serde(rename = "inputs")]
    pub inputs: Vec<crate::models::Input>,
    #[serde(rename = "invalidBefore", skip_serializing_if = "Option::is_none")]
    pub invalid_before: Option<String>,
    #[serde(rename = "invalidHereafter", skip_serializing_if = "Option::is_none")]
    pub invalid_hereafter: Option<String>,
    #[serde(rename = "metadata")]
    pub metadata: ::std::collections::HashMap<String, crate::models::Metadata>,
    #[serde(rename = "tags")]
    pub tags: ::std::collections::HashMap<String, crate::models::Metadata>,
    #[serde(rename = "version")]
    pub version: crate::models::MarloweVersion,
}

impl PostTransactionsRequest {
    pub fn new(
        inputs: Vec<crate::models::Input>,
        metadata: ::std::collections::HashMap<String, crate::models::Metadata>,
        tags: ::std::collections::HashMap<String, crate::models::Metadata>,
        version: crate::models::MarloweVersion,
    ) -> PostTransactionsRequest {
        PostTransactionsRequest {
            inputs,
            invalid_before: None,
            invalid_hereafter: None,
            metadata,
            tags,
            version,
        }
    }
}
