/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostWithdrawalsRequest {
    #[serde(rename = "payouts")]
    pub payouts: Vec<String>,
}

impl PostWithdrawalsRequest {
    pub fn new(payouts: Vec<String>) -> PostWithdrawalsRequest {
        PostWithdrawalsRequest { payouts }
    }
}
