/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostWithdrawalsRequest {
    #[serde(rename = "payouts")]
    pub payouts: Vec<String>,
}

impl PostWithdrawalsRequest {
    pub fn new(payouts: Vec<String>) -> PostWithdrawalsRequest {
        PostWithdrawalsRequest {
            payouts,
        }
    }
}


