/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoleTokenConfig {
    /// A cardano address
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "metadata")]
    pub metadata: Box<crate::models::TokenMetadata>,
}

impl RoleTokenConfig {
    pub fn new(address: String, metadata: crate::models::TokenMetadata) -> RoleTokenConfig {
        RoleTokenConfig {
            address,
            metadata: Box::new(metadata),
        }
    }
}


