/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

pub type AdditionalRolesConfigProp =
    ::std::collections::HashMap<String, crate::models::RoleTokenConfig>;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RolesConfig {
    PolicyId(String),
    AdditionalRolesConfigProp(AdditionalRolesConfigProp),
}
