/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RoleTokenConfig {
    /// A cardano address, in Bech32 format
    Address(String),
    AddressAndMetadata(crate::models::AddressAndMetadata),
    MetadataAndScript(crate::models::MetadataAndScript),
    MetadataAndRecipients(crate::models::MetadataAndRecipients),
}
