/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoleTokenConfigOneOf {
    /// A cardano address, in Bech32 format
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "metadata")]
    pub metadata: Box<crate::models::TokenMetadata>,
}

impl RoleTokenConfigOneOf {
    pub fn new(address: String, metadata: crate::models::TokenMetadata) -> RoleTokenConfigOneOf {
        RoleTokenConfigOneOf {
            address,
            metadata: Box::new(metadata),
        }
    }
}


