/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

use std::collections::HashMap;

use super::RoleTokenConfig;

pub type AdditionalRolesConfigProp = HashMap<String, RoleTokenConfig>;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RolesConfig {
    PolicyId(String),
    AdditionalRolesConfigProp(AdditionalRolesConfigProp),
}
