/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// StakingPointer : A Plutus staking pointer.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StakingPointer {
    #[serde(rename = "stakingHash")]
    pub staking_hash: Vec<i32>,
}

impl StakingPointer {
    /// A Plutus staking pointer.
    pub fn new(staking_hash: Vec<i32>) -> StakingPointer {
        StakingPointer { staking_hash }
    }
}
