/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TextEnvelope {
    #[serde(rename = "cborHex")]
    pub cbor_hex: String,
    #[serde(rename = "description")]
    pub description: String,
    /// What type of data is encoded in the CBOR Hex. Valid values include \"Tx <era>\", \"TxBody <era>\", and \"ShelleyTxWitness <era>\" where <era> is one of \"BabbageEra\", \"ConwayEra\".
    #[serde(rename = "type")]
    pub r#type: String,
}

impl TextEnvelope {
    pub fn new(cbor_hex: String, description: String, r#type: String) -> TextEnvelope {
        TextEnvelope {
            cbor_hex,
            description,
            r#type,
        }
    }
}


