/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TextEnvelope {
    #[serde(rename = "cborHex")]
    pub cbor_hex: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl TextEnvelope {
    pub fn new(cbor_hex: String, description: String, r#type: String) -> TextEnvelope {
        TextEnvelope {
            cbor_hex,
            description,
            r#type,
        }
    }
}


