/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TimeInterval {
    #[serde(rename = "time_interval_start")]
    Start,
    #[serde(rename = "time_interval_end")]
    End,

}

impl ToString for TimeInterval {
    fn to_string(&self) -> String {
        match self {
            Self::Start => String::from("time_interval_start"),
            Self::End => String::from("time_interval_end"),
        }
    }
}

impl Default for TimeInterval {
    fn default() -> TimeInterval {
        Self::Start
    }
}




