/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// Token : A token with a currency symbol (minting policy ID) and token name.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Token {
    #[serde(rename = "currency_symbol")]
    pub currency_symbol: String,
    #[serde(rename = "token_name")]
    pub token_name: String,
}

impl Token {
    /// A token with a currency symbol (minting policy ID) and token name.
    pub fn new(currency_symbol: String, token_name: String) -> Token {
        Token {
            currency_symbol,
            token_name,
        }
    }
}
