/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenInAccount {
    #[serde(rename = "amount_of_token")]
    pub amount_of_token: Box<crate::models::Token>,
    #[serde(rename = "in_account")]
    pub in_account: Box<crate::models::Party>,
}

impl TokenInAccount {
    pub fn new(amount_of_token: crate::models::Token, in_account: crate::models::Party) -> TokenInAccount {
        TokenInAccount {
            amount_of_token: Box::new(amount_of_token),
            in_account: Box::new(in_account),
        }
    }
}


