/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{LabelRef, Token};

/// TokenObject : A token with a currency symbol (minting policy ID) and token name.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TokenObject {
    Token(Token),
    LabelRef(LabelRef),
}
