/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Token : A token with a currency symbol (minting policy ID) and token name.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Token {
    #[serde(rename = "currency_symbol")]
    pub currency_symbol: String,
    #[serde(rename = "token_name")]
    pub token_name: String,
}

impl Token {
    /// A token with a currency symbol (minting policy ID) and token name.
    pub fn new(currency_symbol: String, token_name: String) -> Token {
        Token {
            currency_symbol,
            token_name,
        }
    }
}


