/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransactionWarningOneOf3 : A variable-name shadowing warning.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionWarningOneOf3 {
    #[serde(rename = "had_value")]
    pub had_value: i32,
    #[serde(rename = "is_now_assigned")]
    pub is_now_assigned: i32,
    #[serde(rename = "value_id")]
    pub value_id: String,
}

impl TransactionWarningOneOf3 {
    /// A variable-name shadowing warning.
    pub fn new(had_value: i32, is_now_assigned: i32, value_id: String) -> TransactionWarningOneOf3 {
        TransactionWarningOneOf3 {
            had_value,
            is_now_assigned,
            value_id,
        }
    }
}


