/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransactionInputTxInterval : Time interval.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionInputTxInterval {
    #[serde(rename = "from")]
    pub from: i32,
    #[serde(rename = "to")]
    pub to: i32,
}

impl TransactionInputTxInterval {
    /// Time interval.
    pub fn new(from: i32, to: i32) -> TransactionInputTxInterval {
        TransactionInputTxInterval {
            from,
            to,
        }
    }
}


