/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransactionInput : Marlowe transaction input.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionInput {
    #[serde(rename = "tx_inputs")]
    pub tx_inputs: Vec<crate::models::Input>,
    #[serde(rename = "tx_interval")]
    pub tx_interval: Box<crate::models::TransactionInputTxInterval>,
}

impl TransactionInput {
    /// Marlowe transaction input.
    pub fn new(tx_inputs: Vec<crate::models::Input>, tx_interval: crate::models::TransactionInputTxInterval) -> TransactionInput {
        TransactionInput {
            tx_inputs,
            tx_interval: Box::new(tx_interval),
        }
    }
}


