/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// TransactionWarning : A transaction semantics warning.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TransactionWarning {
    NonPositiveDeposit(crate::models::NonPositiveDeposit),
    NonPositivePayment(crate::models::NonPositivePayment),
    PartialPayment(crate::models::PartialPayment),
    VariableShadowing(crate::models::VariableShadowing),
    AssertFail(crate::models::AssertFail),
}
