/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// TransactionErrorOneOf : An invalid time interval.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionErrorOneOf {
    #[serde(rename = "context")]
    pub context: Box<crate::models::IntervalError>,
    #[serde(rename = "error")]
    pub error: Error,
}

impl TransactionErrorOneOf {
    /// An invalid time interval.
    pub fn new(context: crate::models::IntervalError, error: Error) -> TransactionErrorOneOf {
        TransactionErrorOneOf {
            context: Box::new(context),
            error,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "TEIntervalError")]
    TeIntervalError,
}

impl Default for Error {
    fn default() -> Error {
        Self::TeIntervalError
    }
}
