/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransactionOutputOneOf : Marlowe transaction output information.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionOutputOneOf {
    #[serde(rename = "contract")]
    pub contract: Box<crate::models::Contract>,
    #[serde(rename = "payments")]
    pub payments: Vec<crate::models::Payment>,
    #[serde(rename = "state")]
    pub state: Box<crate::models::MarloweState>,
    #[serde(rename = "warnings")]
    pub warnings: Vec<crate::models::TransactionWarning>,
}

impl TransactionOutputOneOf {
    /// Marlowe transaction output information.
    pub fn new(contract: crate::models::Contract, payments: Vec<crate::models::Payment>, state: crate::models::MarloweState, warnings: Vec<crate::models::TransactionWarning>) -> TransactionOutputOneOf {
        TransactionOutputOneOf {
            contract: Box::new(contract),
            payments,
            state: Box::new(state),
            warnings,
        }
    }
}


