/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TxHeader {
    #[serde(rename = "block", skip_serializing_if = "Option::is_none")]
    pub block: Option<Box<crate::models::BlockHeader>>,
    #[serde(rename = "continuations", skip_serializing_if = "Option::is_none")]
    pub continuations: Option<String>,
    /// A reference to a transaction output with a transaction ID and index.
    #[serde(rename = "contractId")]
    pub contract_id: String,
    #[serde(rename = "metadata")]
    pub metadata: ::std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "status")]
    pub status: crate::models::TxStatus,
    #[serde(rename = "tags")]
    pub tags: ::std::collections::HashMap<String, serde_json::Value>,
    /// The hex-encoded identifier of a Cardano transaction
    #[serde(rename = "transactionId")]
    pub transaction_id: String,
    /// A reference to a transaction output with a transaction ID and index.
    #[serde(rename = "utxo", skip_serializing_if = "Option::is_none")]
    pub utxo: Option<String>,
}

impl TxHeader {
    pub fn new(contract_id: String, metadata: ::std::collections::HashMap<String, serde_json::Value>, status: crate::models::TxStatus, tags: ::std::collections::HashMap<String, serde_json::Value>, transaction_id: String) -> TxHeader {
        TxHeader {
            block: None,
            continuations: None,
            contract_id,
            metadata,
            status,
            tags,
            transaction_id,
            utxo: None,
        }
    }
}


