/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TxOutputError : Marlowe transaction error.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TxOutputError {
    #[serde(rename = "transaction_error")]
    pub transaction_error: Box<crate::models::TransactionError>,
}

impl TxOutputError {
    /// Marlowe transaction error.
    pub fn new(transaction_error: crate::models::TransactionError) -> TxOutputError {
        TxOutputError {
            transaction_error: Box::new(transaction_error),
        }
    }
}


