/*
 * Marlowe Runtime REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TxStatus : The status of a transaction on the local node.

/// The status of a transaction on the local node.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TxStatus {
    #[serde(rename = "unsigned")]
    Unsigned,
    #[serde(rename = "submitted")]
    Submitted,
    #[serde(rename = "confirmed")]
    Confirmed,

}

impl ToString for TxStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Unsigned => String::from("unsigned"),
            Self::Submitted => String::from("submitted"),
            Self::Confirmed => String::from("confirmed"),
        }
    }
}

impl Default for TxStatus {
    fn default() -> TxStatus {
        Self::Unsigned
    }
}




