/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// Value : A time-varying expression that evaluates to a boolean

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Value {
    TokenInAccount(crate::models::TokenInAccount),
    TokenAmount(i64),
    Negate(crate::models::Negate),
    Add(crate::models::Add),
    Minus(crate::models::Minus),
    Multiply(crate::models::Multiply),
    Divide(crate::models::Divide),
    ValueOfChoice(crate::models::ValueOfChoice),
    TimeInterval(crate::models::TimeInterval),
    UseValue(crate::models::UseValue),
    IfValue(crate::models::IfValue),
}
