/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// ValueObject : A time-varying expression that evaluates to a boolean

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValueObject {
    #[serde(rename = "amount_of_token")]
    pub amount_of_token: Box<crate::models::TokenObject>,
    #[serde(rename = "in_account")]
    pub in_account: Box<crate::models::PartyObject>,
    #[serde(rename = "negate")]
    pub negate: Box<crate::models::ValueObject>,
    #[serde(rename = "add")]
    pub add: Box<crate::models::ValueObject>,
    #[serde(rename = "and")]
    pub and: Box<crate::models::ValueObject>,
    #[serde(rename = "minus")]
    pub minus: Box<crate::models::ValueObject>,
    #[serde(rename = "value")]
    pub value: Box<crate::models::ValueObject>,
    #[serde(rename = "multiply")]
    pub multiply: Box<crate::models::ValueObject>,
    #[serde(rename = "times")]
    pub times: Box<crate::models::ValueObject>,
    #[serde(rename = "by")]
    pub by: Box<crate::models::ValueObject>,
    #[serde(rename = "divide")]
    pub divide: Box<crate::models::ValueObject>,
    #[serde(rename = "value_of_choice")]
    pub value_of_choice: Box<crate::models::ChoiceIdObject>,
    #[serde(rename = "use_value")]
    pub use_value: String,
    #[serde(rename = "else")]
    pub r#else: Box<crate::models::ValueObject>,
    #[serde(rename = "if")]
    pub r#if: Box<crate::models::ObservationObject>,
    #[serde(rename = "then")]
    pub then: Box<crate::models::ValueObject>,
    /// An arbitrary text identifier for an object in a Marlowe object bundle.
    #[serde(rename = "ref")]
    pub r#ref: String,
}

impl ValueObject {
    /// A time-varying expression that evaluates to a boolean
    pub fn new(
        amount_of_token: crate::models::TokenObject,
        in_account: crate::models::PartyObject,
        negate: crate::models::ValueObject,
        add: crate::models::ValueObject,
        and: crate::models::ValueObject,
        minus: crate::models::ValueObject,
        value: crate::models::ValueObject,
        multiply: crate::models::ValueObject,
        times: crate::models::ValueObject,
        by: crate::models::ValueObject,
        divide: crate::models::ValueObject,
        value_of_choice: crate::models::ChoiceIdObject,
        use_value: String,
        r#else: crate::models::ValueObject,
        r#if: crate::models::ObservationObject,
        then: crate::models::ValueObject,
        r#ref: String,
    ) -> ValueObject {
        ValueObject {
            amount_of_token: Box::new(amount_of_token),
            in_account: Box::new(in_account),
            negate: Box::new(negate),
            add: Box::new(add),
            and: Box::new(and),
            minus: Box::new(minus),
            value: Box::new(value),
            multiply: Box::new(multiply),
            times: Box::new(times),
            by: Box::new(by),
            divide: Box::new(divide),
            value_of_choice: Box::new(value_of_choice),
            use_value,
            r#else: Box::new(r#else),
            r#if: Box::new(r#if),
            then: Box::new(then),
            r#ref,
        }
    }
}
