/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValueObjectOneOf7 {
    #[serde(rename = "else")]
    pub r#else: Box<crate::models::ValueObject>,
    #[serde(rename = "if")]
    pub r#if: Box<crate::models::ObservationObject>,
    #[serde(rename = "then")]
    pub then: Box<crate::models::ValueObject>,
}

impl ValueObjectOneOf7 {
    pub fn new(r#else: crate::models::ValueObject, r#if: crate::models::ObservationObject, then: crate::models::ValueObject) -> ValueObjectOneOf7 {
        ValueObjectOneOf7 {
            r#else: Box::new(r#else),
            r#if: Box::new(r#if),
            then: Box::new(then),
        }
    }
}


