/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValueOneOf8 {
    #[serde(rename = "else")]
    pub r#else: Box<crate::models::Value>,
    #[serde(rename = "if")]
    pub r#if: Box<crate::models::Observation>,
    #[serde(rename = "then")]
    pub then: Box<crate::models::Value>,
}

impl ValueOneOf8 {
    pub fn new(r#else: crate::models::Value, r#if: crate::models::Observation, then: crate::models::Value) -> ValueOneOf8 {
        ValueOneOf8 {
            r#else: Box::new(r#else),
            r#if: Box::new(r#if),
            then: Box::new(then),
        }
    }
}


