/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValueOneOf {
    #[serde(rename = "amount_of_token")]
    pub amount_of_token: Box<crate::models::Token>,
    #[serde(rename = "in_account")]
    pub in_account: Box<crate::models::Party>,
}

impl ValueOneOf {
    pub fn new(amount_of_token: crate::models::Token, in_account: crate::models::Party) -> ValueOneOf {
        ValueOneOf {
            amount_of_token: Box::new(amount_of_token),
            in_account: Box::new(in_account),
        }
    }
}


