/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValueObjectOneOf3 {
    #[serde(rename = "minus")]
    pub minus: Box<crate::models::ValueObject>,
    #[serde(rename = "value")]
    pub value: Box<crate::models::ValueObject>,
}

impl ValueObjectOneOf3 {
    pub fn new(minus: crate::models::ValueObject, value: crate::models::ValueObject) -> ValueObjectOneOf3 {
        ValueObjectOneOf3 {
            minus: Box::new(minus),
            value: Box::new(value),
        }
    }
}


