/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValueObjectOneOf1 {
    #[serde(rename = "negate")]
    pub negate: Box<crate::models::ValueObject>,
}

impl ValueObjectOneOf1 {
    pub fn new(negate: crate::models::ValueObject) -> ValueObjectOneOf1 {
        ValueObjectOneOf1 {
            negate: Box::new(negate),
        }
    }
}


