/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValueOneOf2 {
    #[serde(rename = "add")]
    pub add: Box<crate::models::Value>,
    #[serde(rename = "and")]
    pub and: Box<crate::models::Value>,
}

impl ValueOneOf2 {
    pub fn new(add: crate::models::Value, and: crate::models::Value) -> ValueOneOf2 {
        ValueOneOf2 {
            add: Box::new(add),
            and: Box::new(and),
        }
    }
}


