/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValueOneOf7 {
    #[serde(rename = "use_value")]
    pub use_value: String,
}

impl ValueOneOf7 {
    pub fn new(use_value: String) -> ValueOneOf7 {
        ValueOneOf7 {
            use_value,
        }
    }
}


