/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// ValueObject : A time-varying expression that evaluates to a boolean

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ValueObject {
    TokenInAccount(crate::models::TokenInAccountObject),
    TokenAmount(i64),
    Negate(crate::models::NegateObject),
    Add(crate::models::AddObject),
    Minus(crate::models::MinusObject),
    Multiply(crate::models::MultiplyObject),
    Divide(crate::models::DivideObject),
    ValueOfChoice(crate::models::ValueOfChoiceObject),
    TimeInterval(crate::models::TimeInterval),
    UseValue(crate::models::UseValue),
    IfValue(crate::models::IfValueObject),
    LabelRef(crate::models::LabelRef),
}
