/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValueOfChoiceObject {
    #[serde(rename = "value_of_choice")]
    pub value_of_choice: Box<crate::models::ChoiceIdObject>,
}

impl ValueOfChoiceObject {
    pub fn new(value_of_choice: crate::models::ChoiceIdObject) -> ValueOfChoiceObject {
        ValueOfChoiceObject {
            value_of_choice: Box::new(value_of_choice),
        }
    }
}


