/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValueOneOf7 {
    #[serde(rename = "use_value")]
    pub use_value: String,
}

impl ValueOneOf7 {
    pub fn new(use_value: String) -> ValueOneOf7 {
        ValueOneOf7 {
            use_value,
        }
    }
}


