/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{
    Add, Divide, IfValue, Minus, Multiply, Negate, TimeInterval, TokenInAccount, UseValue,
    ValueOfChoice,
};

/// Value : A time-varying expression that evaluates to a boolean

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Value {
    TokenInAccount(TokenInAccount),
    TokenAmount(i64),
    Negate(Negate),
    Add(Add),
    Minus(Minus),
    Multiply(Multiply),
    Divide(Divide),
    ValueOfChoice(ValueOfChoice),
    TimeInterval(TimeInterval),
    UseValue(UseValue),
    IfValue(IfValue),
}
