/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValueObjectOneOf1 {
    #[serde(rename = "negate")]
    pub negate: Box<crate::models::ValueObject>,
}

impl ValueObjectOneOf1 {
    pub fn new(negate: crate::models::ValueObject) -> ValueObjectOneOf1 {
        ValueObjectOneOf1 {
            negate: Box::new(negate),
        }
    }
}


