/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValueObjectOneOf3 {
    #[serde(rename = "minus")]
    pub minus: Box<crate::models::ValueObject>,
    #[serde(rename = "value")]
    pub value: Box<crate::models::ValueObject>,
}

impl ValueObjectOneOf3 {
    pub fn new(minus: crate::models::ValueObject, value: crate::models::ValueObject) -> ValueObjectOneOf3 {
        ValueObjectOneOf3 {
            minus: Box::new(minus),
            value: Box::new(value),
        }
    }
}


