/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValueObjectOneOf5 {
    #[serde(rename = "by")]
    pub by: Box<crate::models::ValueObject>,
    #[serde(rename = "divide")]
    pub divide: Box<crate::models::ValueObject>,
}

impl ValueObjectOneOf5 {
    pub fn new(by: crate::models::ValueObject, divide: crate::models::ValueObject) -> ValueObjectOneOf5 {
        ValueObjectOneOf5 {
            by: Box::new(by),
            divide: Box::new(divide),
        }
    }
}


