/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValueObjectOneOf2 {
    #[serde(rename = "add")]
    pub add: Box<crate::models::ValueObject>,
    #[serde(rename = "and")]
    pub and: Box<crate::models::ValueObject>,
}

impl ValueObjectOneOf2 {
    pub fn new(add: crate::models::ValueObject, and: crate::models::ValueObject) -> ValueObjectOneOf2 {
        ValueObjectOneOf2 {
            add: Box::new(add),
            and: Box::new(and),
        }
    }
}


