/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// WithdrawTxEnvelope : The \"type\" property of \"tx\" must be \"Tx BabbageEra\" or \"Tx ConwayEra\"

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WithdrawTxEnvelope {
    #[serde(rename = "tx")]
    pub tx: Box<crate::models::TextEnvelope>,
    /// The hex-encoded identifier of a Cardano transaction
    #[serde(rename = "withdrawalId")]
    pub withdrawal_id: String,
}

impl WithdrawTxEnvelope {
    /// The \"type\" property of \"tx\" must be \"Tx BabbageEra\" or \"Tx ConwayEra\"
    pub fn new(tx: crate::models::TextEnvelope, withdrawal_id: String) -> WithdrawTxEnvelope {
        WithdrawTxEnvelope {
            tx: Box::new(tx),
            withdrawal_id,
        }
    }
}
