/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// WithdrawTxBodyEnvelope : The \"type\" property of \"txBody\" must be \"TxBody BabbageEra\" or \"TxBody ConwayEra\"



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WithdrawTxBodyEnvelope {
    #[serde(rename = "txBody")]
    pub tx_body: Box<crate::models::TextEnvelope>,
    /// The hex-encoded identifier of a Cardano transaction
    #[serde(rename = "withdrawalId")]
    pub withdrawal_id: String,
}

impl WithdrawTxBodyEnvelope {
    /// The \"type\" property of \"txBody\" must be \"TxBody BabbageEra\" or \"TxBody ConwayEra\"
    pub fn new(tx_body: crate::models::TextEnvelope, withdrawal_id: String) -> WithdrawTxBodyEnvelope {
        WithdrawTxBodyEnvelope {
            tx_body: Box::new(tx_body),
            withdrawal_id,
        }
    }
}


